databases:
  - name: fsp-bluefin
    user: roderick
    plan: free
    region: oregon

services:
  - type: web
    name: fsp-bluefin
    plan: free
    region: oregon
    branch: main
    env: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "rails s"
    envVars:
      - key: DATABASE_URL
        fromDatabase:
          name: fsp-bluefin
          property: connectionString
      - key: RAILS_MASTER_KEY
        sync: false
